model_type: 0
model_name: GraphMultiHead

marker: single

cuda_name: cuda:0

work_dir: cls_sider
batch_size:
  train: 256
  val: 256
  test: 256
lr: 0.001
num_epoch: 150
log_interval: 2
split_type: scaffold
seed: 42

dataset_name: sider
dataset_path: datasets/seed_42/finetune_set/sider.csv
testset_path: datasets/seed_42/test_set/sider.csv
cleanset_path: datasets/seed_42/test_set/sider_clean.csv
predictset_path: datasets/seed_42/merged_training_set.csv
to_fill_training_set_path: datasets/seed_42/to_fill_training_set/sider.csv


dataset_type:
  scale: 1
  select_type: zeroshot
  train: 0.8
  val: 0.1
  test: 0.1



model:

  drug_module:
    module_name:
      - GATConv
      - GCNConv
    input_drug_feature_dim:  78
    output_drug_feature_dim: 128
    num_labels: 27 # vary with dataset
    layer_num: 2

    gnn_layers:
      -
        intput: 78
        output: 78
        dropout: 0.0
        feature_pre_dropout: 0
        heads: 10
      -
        intput: 780
        output: 780
        dropout: 0.0
        feature_pre_dropout: 0


    linear_layers:
      -
        operate_name: linear
        param:
          - 1560
          - 500
      -
        operate_name: relu
      -
        operate_name: dropout
        param: 0.5
      -
        operate_name: linear
        param:
          - 500
          - 128

    graph_pooling: max_mean
    dropout: 0.5

