model_type: 0
model_name: GraphMultiHead

marker: multi_finetune

cuda_name: cuda:2

work_dir: reg_freesolv
batch_size:
  train: 128
  val: 128
  test: 128
lr: 0.001
num_epoch: 150
log_interval: 2
split_type: scaffold
seed: 42

selected_task: 7
dataset_name: freesolv
pretrained_model_path: /home/nas/wwj/molnet_multi_head/exp/scaffold_seed_1/multi_pretrain/pretrain__20240323114533/GraphMultiHead_epoch_10_best_model_regression_task_freesolv.pt
dataset_path: datasets/seed_42/finetune_set/freesolv.csv
testset_path: datasets/seed_42/test_set/freesolv.csv
cleanset_path: datasets/seed_42/test_set/freesolv_clean.csv
task_output_dims: [1, 1, 2, 27, 12, 617, 1, 1, 1]

dataset_type:
  scale: 1
  select_type: zeroshot
  dataset_path: datasets/raw_data/molnet/finetune_set/freesolv.csv
  train: 0.8
  val: 0.1
  test: 0.1



model:

  drug_module:
    module_name:
      - GATConv
      - GCNConv
    input_drug_feature_dim:  78
    output_drug_feature_dim: 128
    num_labels: 1 # vary with dataset
    layer_num: 2

    gnn_layers:
      -
        intput: 78
        output: 78
        dropout: 0.0
        feature_pre_dropout: 0
        heads: 10
      -
        intput: 780
        output: 780
        dropout: 0.0
        feature_pre_dropout: 0


    linear_layers:
      -
        operate_name: linear
        param:
          - 1560
          - 500
      -
        operate_name: relu
      -
        operate_name: dropout
        param: 0.5
      -
        operate_name: linear
        param:
          - 500
          - 128


    graph_pooling: max_mean
    dropout: 0.5


